name: SanLite CI - Push

on:
  push:
    branches: 
      - '**'
    tags-ignore:
      - '**'

jobs:
  build-test-checkstyle:
    runs-on: ubuntu-latest
    name: Build, test & checkstyle

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1.0.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build with Maven & check for Checkstyle violations
        run: mvn -B package -DskipTests -Dcheckstyle.skip=false --file pom.xml
      
      - name: Test with Maven
        run: mvn test
